name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd DockerImage && docker build . --file Dockerfile --tag ragumanjegowda/docker:$(date '+%Y%m%d%H%M%S')

